version: "3.9"

services:
  backend:
    build: .
    container_name: backend-app-4.O-service
    ports:
      - "5000:5000"
    env_file:
      - .env.local
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo-service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_v2:/data/db

volumes:
  mongo_data_v2:
